### ISSUE TITLE
Expand on README

### ISSUE THREAD

**Issue by orta** [artsy/artsy-auth#4]
Any chance you can make the README explain where `'some-secret'` should come from 

```rb
  # override application to decode token and allow only users with `tester` role
  def authorized_artsy_token?(token)
    decoded_token, _headers = JWT.decode(token, 'some-secret')
    decoded_token['roles'].include? 'tester'
  end
```

**Comment by orta** [comment]
Found the code in Bearden: https://github.com/artsy/bearden/blob/master/app/controllers/application_controller.rb#L26

**Comment by ashkan18** [comment]
yes, it's `secret` between Artsy and consumer app.
